### ISSUE TITLE
gstudio no longer available?

### ISSUE THREAD

**Issue by drmel222** [dyerlab/gstudio#13]
Hi there,
Im getting the message:
Warning in install.packages :
  package ‘gstudio’ is not available (for R version 3.6.2)

Is this package no longer available?

**Comment by dyerlab** [comment]
Sorry I missed this one.

Look at github.com/dyerlab/gstudio for instructions.


--
Rodney J. Dyer, PhD
Director, Center for Environmental Studies
<https://ces.vcu.edu/>
Virginia Commonwealth University
http://dyerlab.com
