### ISSUE TITLE
gstudio: write_population function not avilabel

### ISSUE THREAD

**Issue by hackerzone85** [dyerlab/gstudio#2]
Hi Mr. Dyer
When i install gstudio_v1.3 form "https://cran.r-project.org/src/contrib/Archive/gstudio/" it show the error about write_population
> write_population(df, "/home/blab/Desktop/Darwin/mydata.txt", mode = "genepop")
Error in if (!is.null(stratum) & !(stratum %in% names(df))) stop("You have specified a non-existant
stratum to be used, how about one the data.frame actually has?") : argument is of length zero

**Comment by dyerlab** [comment]
Install it from here.  use:

require(devtools)
install_github("dyerlab/gstudio")
