### ISSUE TITLE
3.3.1 installation fails

### ISSUE THREAD

**Issue by Froodrice** [dyerlab/gstudio#3]
Hello Dr. Dyer,
I'm installing gstudio on PC running Windows 10- R vers 3.3.1.
Following devtools installation and the install_github("dyerlab/gstudio") command:
packages successfully installed: ggmap, plotGogleMaps, popgraph
Error thrown on gstudio source:
* installing *source* package 'gstudio' ...
** R
** data
** inst
** tests
** preparing package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called 'geosphere'
ERROR: lazy loading failed for package 'gstudio'
* removing 'C:/Users/Boreas/Documents/R/win-library/3.3/gstudio'
Error: Command failed (1)

To continue installing, I'm having to run the install-github("dyerlab/gstudio") command each time and see what package is needed a the error and install manually.

Might be useful to post these as dependencies in the download or within a visible text file to make installation easier since install.package("gstudio") isn't currently supported.
geosphere, mapproj, proto, maptools, spacetime, sampling

-Stephen Rice

**Comment by dyerlab** [comment]
It is odd that there does not seem to be a dependencies=TRUE option...  I've got a few more changes to make and then I'll put it on CRAN.
