### ISSUE TITLE
Installation fail

### ISSUE THREAD

**Issue by coramane** [dyerlab/gstudio#4]
Hi,
I'm installing **gstudio** on PC running Windows 10- R vers 3.3.1, following devtools installation and the install_github("dyerlab/gstudio"). But it fails, stating:
 "Error in namespaceExport(ns, exports) : undefined exports: Hes, Hos." 
I thought this might be related to **roxygen2 package** and updated it, but this didn't help either. Here is the full error:

install_github("dyerlab/gstudio")
Downloading GitHub repo dyerlab/gstudio@master
from URL https://api.github.com/repos/dyerlab/gstudio/zipball/master
Installing gstudio
"C:/PROGRA~1/R/R-33~1.1/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/EMRAH/AppData/Local/Temp/RtmpURaWrl/devtools21486e081de/dyerlab-gstudio-081b8f1" --library="C:/Users/EMRAH/Documents/R/win-library/3.3"  \
  --install-tests 

** installing *source* package 'gstudio' ...
** R
** data
** inst
** tests
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
*** arch - i386
Error in namespaceExport(ns, exports) : undefined exports: Hes, Hos
Error: loading failed
Execution halted
*** arch - x64
Error in namespaceExport(ns, exports) : undefined exports: Hes, Hos
Error: loading failed
Execution halted
ERROR: loading failed for 'i386', 'x64'
* removing 'C:/Users/EMRAH/Documents/R/win-library/3.3/gstudio'
Error: Command failed (1)

**Comment by dyerlab** [comment]
Hmmm.  Looks like I messed something up in the latest build.  I'll look at
it in the morning.

R

On Thu, Jul 7, 2016 at 7:45 PM, coramane <notifications@github.com> wrote:

> Hi,
> I'm installing *gstudio* on PC running Windows 10- R vers 3.3.1,
> following devtools installation and the install_github("dyerlab/gstudio").
> But it fails, stating:
> "Error in namespaceExport(ns, exports) : undefined exports: Hes, Hos."
> I thought this might be related to *roxygen2 package* and updated it, but
> this didn't help either. Here is the full error:
>
> install_github("dyerlab/gstudio")
> Downloading GitHub repo dyerlab/gstudio@master
> from URL https://api.github.com/repos/dyerlab/gstudio/zipball/master
> Installing gstudio
> "C:/PROGRA~1/R/R-33~1.1/bin/x64/R" --no-site-file --no-environ --no-save
> --no-restore --quiet CMD INSTALL \
> "C:/Users/EMRAH/AppData/Local/Temp/RtmpURaWrl/devtools21486e081de/dyerlab-gstudio-081b8f1"
> --library="C:/Users/EMRAH/Documents/R/win-library/3.3" \
> --install-tests
>
> ** installing *source* package 'gstudio' ...
> ** R
> ** data
> ** inst
> ** tests
> ** preparing package for lazy loading
> ** help
> *** installing help indices
> ** building package indices
> ** installing vignettes
> ** testing if installed package can be loaded
> *** arch - i386
> Error in namespaceExport(ns, exports) : undefined exports: Hes, Hos
> Error: loading failed
> Execution halted
> *** arch - x64
> Error in namespaceExport(ns, exports) : undefined exports: Hes, Hos
> Error: loading failed
> Execution halted
> ERROR: loading failed for 'i386', 'x64'
>
>    - removing 'C:/Users/EMRAH/Documents/R/win-library/3.3/gstudio' Error:
>    Command failed (1)
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/dyerlab/gstudio/issues/4>, or mute the thread
> <https://github.com/notifications/unsubscribe/ADodzqGhGgjEgZuXboRuCXURx5nVhxfxks5qTY-FgaJpZM4JHmuQ>
> .
>



-- 
Rodney J. Dyer, PhD
Department of Biology
Center for Environmental Studies
Virginia Commonwealth University
http://dyerlab.bio.vcu.edu

**Comment by dyerlab** [comment]
OK, actually it was very easy.  install it again from github and it should
be fixed.

Let me know if you encounter any other problems.

R

On Thu, Jul 7, 2016 at 7:45 PM, coramane <notifications@github.com> wrote:

> Hi,
> I'm installing *gstudio* on PC running Windows 10- R vers 3.3.1,
> following devtools installation and the install_github("dyerlab/gstudio").
> But it fails, stating:
> "Error in namespaceExport(ns, exports) : undefined exports: Hes, Hos."
> I thought this might be related to *roxygen2 package* and updated it, but
> this didn't help either. Here is the full error:
>
> install_github("dyerlab/gstudio")
> Downloading GitHub repo dyerlab/gstudio@master
> from URL https://api.github.com/repos/dyerlab/gstudio/zipball/master
> Installing gstudio
> "C:/PROGRA~1/R/R-33~1.1/bin/x64/R" --no-site-file --no-environ --no-save
> --no-restore --quiet CMD INSTALL \
> "C:/Users/EMRAH/AppData/Local/Temp/RtmpURaWrl/devtools21486e081de/dyerlab-gstudio-081b8f1"
> --library="C:/Users/EMRAH/Documents/R/win-library/3.3" \
> --install-tests
>
> ** installing *source* package 'gstudio' ...
> ** R
> ** data
> ** inst
> ** tests
> ** preparing package for lazy loading
> ** help
> *** installing help indices
> ** building package indices
> ** installing vignettes
> ** testing if installed package can be loaded
> *** arch - i386
> Error in namespaceExport(ns, exports) : undefined exports: Hes, Hos
> Error: loading failed
> Execution halted
> *** arch - x64
> Error in namespaceExport(ns, exports) : undefined exports: Hes, Hos
> Error: loading failed
> Execution halted
> ERROR: loading failed for 'i386', 'x64'
>
>    - removing 'C:/Users/EMRAH/Documents/R/win-library/3.3/gstudio' Error:
>    Command failed (1)
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/dyerlab/gstudio/issues/4>, or mute the thread
> <https://github.com/notifications/unsubscribe/ADodzqGhGgjEgZuXboRuCXURx5nVhxfxks5qTY-FgaJpZM4JHmuQ>
> .
>



-- 
Rodney J. Dyer, PhD
Department of Biology
Center for Environmental Studies
Virginia Commonwealth University
http://dyerlab.bio.vcu.edu

**Comment by dyerlab** [comment]
Fixed

**Comment by coramane** [comment]
Thanks a lot for your quick response.
DONE (gstudio)

Emrah
