### ISSUE TITLE
install fails with R version 3.4.1

### ISSUE THREAD

**Issue by RaSieb** [dyerlab/gstudio#5]
`> devtools::install_github("dyerlab/gstudio")`
Downloading GitHub repo dyerlab/gstudio@master
from URL https://api.github.com/repos/dyerlab/gstudio/zipball/master
Installing gstudio
trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/ggrepel_0.7.0.tgz'
Content type 'application/x-gzip' length 683726 bytes (667 KB)
"=================================================="
downloaded 667 KB

Installing ggrepel
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/wh/ngnn010j5k3d6b590f225flw0000gn/T/RtmpcpZ0w9/devtools15066d0f0d11/ggrepel'  \
  --library='/Library/Frameworks/R.framework/Versions/3.4/Resources/library' --install-tests 

\* installing *binary* package ‘ggrepel’ ...
\* DONE (ggrepel)
trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/plotGoogleMaps_2.2.tgz'
Content type 'application/x-gzip' length 125592 bytes (122 KB)
"=================================================="
downloaded 122 KB

Installing plotGoogleMaps
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/wh/ngnn010j5k3d6b590f225flw0000gn/T/RtmpcpZ0w9/devtools150618184800/plotGoogleMaps'  \
  --library='/Library/Frameworks/R.framework/Versions/3.4/Resources/library' --install-tests 

\* installing *binary* package ‘plotGoogleMaps’ ...
\* DONE (plotGoogleMaps)
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/wh/ngnn010j5k3d6b590f225flw0000gn/T/RtmpcpZ0w9/devtools150674e133c9/dyerlab-gstudio-af96877'  \
  --library='/Library/Frameworks/R.framework/Versions/3.4/Resources/library' --install-tests 

ERROR: dependency ‘popgraph’ is not available for package ‘gstudio’
\* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/gstudio’
Installation failed: Command failed (1)
`> install.packages("popgraph")`
Warning in install.packages :
  package ‘popgraph’ is not available (for R version 3.4.1)
`> install.packages("gstudio")`
Warning in install.packages :
  package ‘gstudio’ is not available (for R version 3.4.1)

**Comment by dyerlab** [comment]
This can be fixed by:

devtools::install_github("dyerlab/popgraph")

before you attempt to install the gstudio package.  I fixed the front page docs to reflect this difference.

**Comment by RaSieb** [comment]
THANKS!

**Comment by alibat** [comment]
I'm still having this issue, and when I try the suggestion above, I'm getting the error message below. Do you have any further suggestions?

Downloading GitHub repo dyerlab/popgraph@master
from URL https://api.github.com/repos/dyerlab/popgraph/zipball/master
Installing popgraph
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ  \
  --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/_j/shykl5gx7wx0jvc0s5lkj5xr0000gn/T/RtmpASqk35/devtools40403cd947f9/dyerlab-popgraph-1f00752'  \
  --library='/Library/Frameworks/R.framework/Versions/3.5/Resources/library'  \
  --install-tests 

* installing *source* package ‘popgraph’ ...
** R
** data
** inst
** tests
** byte-compile and prepare package for lazy loading
Error : package or namespace load failed for ‘popgraph’ in loadNamespace(package, lib.loc):
 cyclic namespace dependency detected when loading ‘popgraph’, already loading ‘popgraph’
Error : unable to load R code in package ‘popgraph’
ERROR: lazy loading failed for package ‘popgraph’
* removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/popgraph’
Installation failed: Command failed (1)

**Comment by alibat** [comment]
Oops - thanks :)  I had restarted Rstudio, but I restarted my whole computer this morning and it worked. Thanks.

I just got this one warning message at the end of the gstudio install:
Warning: S3 method ‘as.data.frame.genetic_structure’ was declared in NAMESPACE but not found

**Comment by dyerlab** [comment]
Ok. I’ll look into that
