### ISSUE TITLE
Having an issue with installing gstudio

### ISSUE THREAD

**Issue by vjjan91** [dyerlab/gstudio#6]
Current error:

Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called 'ggmaps'
ERROR: lazy loading failed for package 'gstudio'

Perhaps, it is searching for ggmaps instead of trying to search for ggmap?

**Comment by kimh11** [comment]
Also running into the same error. Could these lines in the `namespace` file be the problem?
```
importFrom(ggmaps,google_key)
importFrom(ggmaps,has_google_key)
```

**Comment by kimh11** [comment]
Thank you! Got it installed! 😀
